config/routes.rb
Rails.application.routes.draw do
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :songs do
  resources :likes, only: [:create, :destroy]
  end
  
  resources :users, only: [:index,:show]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:index,:show,:create]

  get'songs/top'=>'songs#top'
  root 'songs#top'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :song_genres, dependent: :destroy
    has_many :songs, through: :song_genres
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :song
  belongs_to :user

  validates_uniqueness_of :song_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy
    has_many :users, through: :entries
end

app/models/situation.rb
class Situation < ApplicationRecord
    has_many :song_situations, dependent: :destroy
    has_many :songs, through: :song_situations
end

app/models/song.rb
class Song < ApplicationRecord
    belongs_to :user

    has_many :song_tags, dependent: :destroy
    has_many :tags, through: :song_tags
    
    has_many :song_genres, dependent: :destroy
    has_many :genres, through: :song_genres

    has_many :song_situations, dependent: :destroy
    has_many :situations, through: :song_situations

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    
    mount_uploader :image, ImageUploader
    
end

app/models/song_genre.rb
class SongGenre < ApplicationRecord
  belongs_to :song
  belongs_to :genre
end

app/models/song_situation.rb
class SongSituation < ApplicationRecord
  belongs_to :song
  belongs_to :situation
end

app/models/song_tag.rb
class SongTag < ApplicationRecord
  belongs_to :song
  belongs_to :tag

end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :song_tags, dependent: :destroy
    has_many :songs, through: :song_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_many :songs, dependent: :destroy
  validates :name, presence: true
  validates :profile, length: { maximum: 200 }
  validates :like_genre, presence: false 
  validates :like_artist, presence: false

   has_many :likes, dependent: :destroy
   has_many :liked_songs, through: :likes, source: :song
   
   has_many :messages, dependent: :destroy
   has_many :entries, dependent: :destroy
  
   has_many :rooms, dependent: :destroy
   
   def already_liked?(song)
    self.likes.exists?(song_id: song.id)
  end

  mount_uploader :image, ImageUploader
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(song_id: params[:song_id]) #user_idとsong_idの二つを代入
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(song_id: params[:song_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
    
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def index
    # ユーザーが参加しているルームのエントリーを取得
    user_entries = Entry.where(user_id: current_user.id).pluck(:room_id)
    
    # ユーザーが参加しているルームの一覧を取得
    @room_lists = Room.where(id: user_entries)
    
    if @room_lists.empty?
      @room_lists_none = "グループに参加していません。"
    end
  end

  def show
    @room = Room.find(params[:id])
      if Entry.where(user_id: current_user.id, room_id: @room.id).present?
        @messages = @room.messages.all
        @message = Message.new
        @entries = @room.entries
      else
        redirect_back(fallback_location: root_path)
      end
  end

  def create
    @room = Room.create
    Entry.create(room_id: @room.id, user_id: current_user.id)
    Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to "/rooms/#{@room.id}"
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

    before_action :authenticate_user!, only: [:new, :create]

    def top 
    end

    def index
        

          if params[:search] == nil
            @Songs = params[:tag_id].present? ? Tag.find(params[:tag_id]).songs : Song.all
          elsif params[:search] == ''
            @Songs = params[:tag_id].present? ? Tag.find(params[:tag_id]).songs : Song.all
          else
      
          @Songs = Song.where("storename LIKE ? OR menu LIKE ? OR place LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
          end

    
    end
    
    def new
        @Song=Song.new
    end

    
    def create
        song = Song.new(song_params)

        song.user_id = current_user.id 

        if song.save!
            redirect_to :action => "index"
        else
            redirect_to :action => "new"
        end
    end

    def edit
        @song = Song.find(params[:id])
    end
     
    def update
        song = Song.find(params[:id])
        if song.update(song_params)
          redirect_to :action => "show", :id => song.id
        else
          redirect_to :action => "new"
        end
    end

    def destroy
      song = Song.find(params[:id])
      song.destroy
      redirect_to action: :index
    end
    

        private
    
            def song_params
            params.require(:song).permit(:name, :artist, :genre_ids, :tag_ids, :situation_ids, :url, :image,:like_genre,:like_artist)
            end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
     def index
      @users=User.all

    end
    
    def show
        @user = User.find(params[:id])
        @currentUserEntry=Entry.where(user_id: current_user.id)
        @userEntry=Entry.where(user_id: @user.id)
        if @user.id == current_user.id
          @msg ="他のユーザーとDMしてみよう！"
        else
          @currentUserEntry.each do |cu|
            @userEntry.each do |u|
              if cu.room_id == u.room_id then
                @isRoom = true
                @roomId = cu.room_id
              end
            end 
          end

          if @isRoom != true
            @room = Room.new
            @entry = Entry.new
          end
    
        end
      end
    end

    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/rooms/index.html.erb
<% if @room_lists.empty? %>
  <%= @room_lists_none %>
<% else %>
  <div class="group-list">
    <ul class="group-list-table">
      <% @room_lists.each do |room| %>
        <div class="group-list-table-each-group">
          <%= link_to "/rooms/#{room.id}" do %>
            <div class="a">
              <div class="group-name">
                <%= room.name %>（<%= room.users.count %>人）
              </div>
              <br>
            </div>
          <% end %>
        </div>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/rooms/show.html.erb
<div class="user-in">
<% @entries.each do |e| %>
    <h3><strong><a href="/users/<%= e.user.id %>"><%= e.user.email%></a></strong></h3>
<% end %>
<p>DM</p>
</div>

<div class="dmMain">
    <% @messages.each do |m| %>
        <strong><%= m.body %></strong>
        <small><%= m.user.email %>さん</small><hr>
    <% end %>

    <%= form_for @message do |f| %>
    <%= f.text_field :body, :placeholder => "メッセージを入力して下さい" , :size => 100 %>
    <%= f.hidden_field :room_id, :value => @room.id %>
    <br>
    <%= f.submit "送信する" %>
    <% end %>
</div>

<%= link_to "ユーザー一覧に戻る", users_path %>


<style>
.user-in{
    text-align:center;
    border:1px solid darkgray;
    background-color:gainsboro;
}
.dmMain{
    padding:30px;
    border:1px solid darkgray;
    background-color:gainsboro;
}
</style>

app/views/songs/edit.html.erb
<%= form_for @song do |f| %>
    <%= f.label :body %>
    <%= f.text_field :body, :size => 140 %> 
    <%= f.submit "編集する" %>
  <% end %>

app/views/songs/index.html.erb
<h1>新しい曲に出会おう！</h1>
  
<%= form_tag songs_path, method: :get, class: 'boards__searchForm' do %>
  <%= select_tag :genre_id,
                  options_from_collection_for_select(Genre.all, :id, :name, params[:genre_id]),
                 {
                    prompt: 'ジャンルを選択',
                    
                   }
    %>

  <%= select_tag :tag_id,
                 options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
                 {
                   prompt: '気分を選択',
                  
                 }
  %>

  <%= select_tag :situation_id,
                 options_from_collection_for_select(Situation.all, :id, :name, params[:situation_id]),
                 {
                   prompt: '場面を選択',
                  
                 }
  %>


  <%= submit_tag '検索する'  %>
<% end %>




<div class="songs-container">
  <% @Songs.each do |t| %>
    <div class="song">
      <%= image_tag t.user.image_url, size: "250x200" if t.user.image? %>
      <%= t.name %>
      <%= t.artist %>
      
    </div>
      <% t.genres.each do |g| %>
      <%= g.name %>
      <% end %> 
    <% t.tags.each do |tag| %>
      <%= tag.name %>
      <% end %> 
    <% t.situations.each do |s| %>
      <%= s.name %>
      <% end %>

      <%= t.url %>

      <%= t.user.email %>

    <% if user_signed_in? %>  
        <% if current_user.already_liked?(t) %>
          <%= link_to song_like_path(id: t.id, song_id: t.id), method: :delete do %>
          <i class="fas fa-heart"></i><%= t.likes.count %>
        <% end %>
        <% else %>
          <%= link_to song_likes_path(id: t.id, song_id: t.id), method: :post do %>
          <i class="far fa-heart"></i><%= t.likes.count %>
        <% end %>
    <% end %>
  <% else %>
  <i class="fas far-heart"><%= t.likes.count %>
  <% end %>
  <%= link_to "投稿者のマイページ", user_path(t.user) %>

  <% if user_signed_in? && current_user.id == t.user_id %>
  <%= link_to "削除する", song_path(t.id), method: :delete %>
  <% end %>

  <% end %>

  
  
  
 <br> <%= link_to "自分の好きな曲をみんなと共有しよう！", new_song_path %>
      <%= link_to "新たな仲間を見つけよう", users_path %>
      <%= link_to "DM一覧", rooms_path %>
  
  

</div>

app/views/songs/new.html.erb
<h1>自分の好きな曲をみんなと共有しよう！</h1>
<h3>新規投稿ページ</h3>
<%= form_for @Song do |f| %>


  <div class="field">
    <%= f.label :曲名 %>
    <%= f.text_field :name, :size => 30 %>
  </div>


  <div class="field">
    <%= f.label :アーティスト名 %>
    <%= f.text_field :artist, :size => 30 %>
  </div>

  <h5>ジャンル:</h5>
  <div class='form-group'>
    <%= f.collection_select :genre_ids, Genre.all, :id, :name, include_blank: "ジャンルを選択"  %>
  </div>


  

  <h5>気分:</h5>
  <div class='form-group'>
    <%= f.collection_select :tag_ids, Tag.all, :id, :name, include_blank: "気分を選択"  %>
  </div>


  
  <h5>場面:</h5>
  <div class='form-group'>
    <%= f.collection_select :situation_ids, Situation.all, :id, :name, include_blank: "場面を選択"  %>
  </div>

  
  <div class="field">
    <%= f.label :URL %>
    <%= f.text_field :url, :size => 30 %>
  </div>







  <%= f.submit "投稿する" %>
<% end %>

<%= link_to "一覧に戻る", songs_path %>

app/views/songs/show.html.erb
<% @Song.tags.each do |tag| %>
    <%= tag.name %>
<% end %>

<% @Song.genres.each do |g| %>
    <%= g.name %>
<% end %>

<% @Song.situations.each do |s| %>
    <%= s.name %>
<% end %>

<h3>Song詳細</h3>
<%= link_to "投稿者のマイページ", user_path(@song.user) %>
<div class="Song">
  <p><%= @Song.body %></p>
  <p><%= @Song.created_at %></p>
    <% if user_signed_in? %>
      <% if current_user.already_liked?(@Song) %>
        <%= link_to Song_like_path(@Song), method: :delete do %>
            <i class="fas fa-heart"></i><%= @song.likes.count %>
          <p>いいねを取り消す</p><%= @Song.likes.count %>
        <% end %>
      <% else %>
      <i class="far fa-heart"></i><%= @song.likes.count %>
        <%= link_to Song_likes_path(@Song), method: :post do %>
            <i class="far fa-heart"></i><%= @song.likes.count %>
          <p>いいね</p><%= @Song.likes.count %>
        <% end %>
      <% end %>
    <% else %>
      <p>いいねの数 = </p><%= @Song.likes.count %>
    <% end %>
  <%= link_to "編集する", edit_Song_path(@Song.id) %>
</div>

<h2>いいねしたユーザー</h2>
<% @Song.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

<%= link_to "Song一覧に戻る", Songs_path %>

app/views/songs/top.html.erb
<!DOCTYPE html>
<%= stylesheet_link_tag 'top', :media => "all" %>

<html>
<div class="first-block">
<h2>新たなリズム<br>
    新たな友達との出会い
</h2>
<li><%= link_to "新規登録はこちら", new_user_registration_path%></li>
</div>


<div class="second-block">
<h2>
ジャンル 気分 場面を検索して<br>新たな曲に出会える！
</h2>

<li><%= link_to "新たな曲を見つけよう", songs_path %></li>
</div>


<div class="third-block">
<h2>
自分の好きな曲を<br>
みんなと共有しよう！
</h2>
<li><%= link_to "好きな曲を投稿する", new_song_path %></li>

</div>

<div class="fourth-block">
<h2>
音楽の価値観が合う人と<br>つながれる♪
</h2>
<li><%= link_to "DMでつながろう", rooms_path %></li>
</div>

</html>

app/views/users/index.html.erb
<h1>DMサンプル</h1>
<h2>User一覧ページ</h2>


<% if user_signed_in? %>
    <h2><%= current_user.email %>でログインしています</h2> 

    <%= link_to "DM一覧", rooms_path %>
    
    <% number = 1%>
    <div class="flex">
        <% @users.each do |u| %>
        <div class="user-in">
            <p>プロフィール No.<%= number %></p>
            <p><%= u.email %>さん</p>
            <p><%= link_to 'ユーザーページへ', user_path(u.id) %></p>
        </div>
        <% number += 1 %>
        <% end %>
    </div>

<% else %>
  <%= link_to "SignUp", new_user_registration_path %>
  <br>
  <%= link_to "SignIn", new_user_session_path %>
<% end %>

<style>
.signOutButton{
    text-decoration:none;
    display:inline-block;
    border:3px solid royalblue;
    background-color:aliceblue;
    padding:5px;
}
.flex{
    display:flex;
    flex-wrap:wrap;    
}
.user-in{
    display:block;
    width:300px;
    text-align:center;
    border:1px solid darkgray;
    background-color:gainsboro;
    flex-shrink: 0;
}
</style>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>MY PAGE</h1>
<%= image_tag @user.image_url, size: "250x187" %>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>
<p>好きなジャンル：<%= @user.like_genre %></p>
<p>好きなアーティスト：<%= @user.like_artist %></p>
<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>



<h2>ユーザーの投稿一覧</h2>
<% @user.songs.each do |t| %>
  <%= t.user.name %>
  <%= t.name %>
<% end %>

<!-- 以下はいいね機能を実装している場合-->
<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_songs.each do |t| %>
  <%= t.user.name %>
  <%= t.name %>
<% end %>


<%= link_to "一覧に戻る", songs_path %>

<h1>ユーザー詳細ページ</h1>

<div class="user-in">
<h2><%= @user.email %></h2>

<% if @user.id == current_user.id %>
    <%= yield %>
<% else %>
    <% if @isRoom == true %>
        <p><%= link_to '新たな仲間とお話ししよう！', room_path(@roomId) %></p>
    <% else %>
        <%= form_for @room do |f| %>
            <%= fields_for @entry do |e|%>
                <% e.hidden_field :user_id, value: @user.id %>
            <% end %>
        <%= f.submit "DMを開始する"%>
        <% end %>
    <% end %>
<% end %>
</div>


<%= link_to "ユーザー一覧に戻る", users_path %>



<style>
.user-in{
    width:300px;
    padding:10px;
    margin:10px;
    text-align:center;
    border:1px solid darkgray;
    background-color:gainsboro;
}
</style>